# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_convert_company_activities_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='main_activity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secondary_activity',
        ),
    ]
