# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_old_activities_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='json_main_activity',
            new_name='main_activity',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='json_secondary_activity',
            new_name='secondary_activity',
        ),
    ]
